project_name: "Sistema de Automacao de Emuladores Android"

emulator:
  type: "MEmu"
  path: "D:\\Program Files\\Microvirt\\MEmu\\memuc.exe"
  instances_limit: 9

logging:
  level: "INFO"
  save_to_file: true
