project_name: "Sistema de Automacao de Emuladores Android"

emulator:
  type: "MEmu"
  path: "D:\\Program Files\\Microvirt\\MEmu\\memuc.exe"
  instances_limit: 16

slot_machine:
  default_duration_minutes: 20
  lines: 9

logging:
  level: "INFO"
  save_to_file: true